# This file is *NOT* reloaded when you use
# 'jekyll serve'. 

# Site settings
baseurl: "/recursion" 
url: "http://soitscometothis.net" 

# Podcast Feed Settings
title:          "Recursion"
email:          your-email-address 
description:    "Two guys talking tech and development." # CHANGE
subtitle:       "Haven't we done this before?"
lang:           en-us
author:         Wayne & Michael 
copyright:      "&#x2117; &amp; &#xA9; 2016"


# Outputting
permalink: /:title/

# Build settings
markdown: kramdown
timezone: America/New_York

# Basic

# Navigation
nav:
  - name:           "About"
    href:           "/about"
  - name:           "Feed"
    href:           "/podcast.rss"
  - name:           "iTunes"
    href:           "https://itunes.apple.com/us/podcast/recursion/id1016507176?mt=2"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
